-- Generated by Matugen (fallback: Tokyo Night)
local M = {}

M.primary = "rgba(33ccffee)"
M.on_primary = "rgba(1a1b26FF)"
M.primary_container = "rgba(33ccffee)"
M.on_primary_container = "rgba(1a1b26FF)"
M.secondary = "rgba(7dcfff)"
M.on_secondary = "rgba(1a1b26FF)"
M.secondary_container = "rgba(7dcfff)"
M.on_secondary_container = "rgba(1a1b26FF)"
M.tertiary = "rgba(bb9af7FF)"
M.on_tertiary = "rgba(1a1b26FF)"
M.tertiary_container = "rgba(bb9af7FF)"
M.on_tertiary_container = "rgba(1a1b26FF)"
M.error = "rgba(f7768eFF)"
M.on_error = "rgba(1a1b26FF)"
M.error_container = "rgba(f7768eFF)"
M.on_error_container = "rgba(1a1b26FF)"
M.background = "rgba(1a1b26FF)"
M.on_background = "rgba(c0caf5FF)"
M.surface = "rgba(24283bFF)"
M.on_surface = "rgba(c0caf5FF)"
M.surface_variant = "rgba(2f3549FF)"
M.on_surface_variant = "rgba(565f89FF)"
M.outline = "rgba(565f89FF)"
M.outline_variant = "rgba(2f3549FF)"

return M
