-- Generated by Matugen
local M = {}

M.primary = "rgba(c7bfffFF)"
M.on_primary = "rgba(2f285fFF)"
M.primary_container = "rgba(463f77FF)"
M.on_primary_container = "rgba(e5deffFF)"
M.secondary = "rgba(c8c3dcFF)"
M.on_secondary = "rgba(312e41FF)"
M.secondary_container = "rgba(474459FF)"
M.on_secondary_container = "rgba(e5dff9FF)"
M.tertiary = "rgba(ecb8ceFF)"
M.on_tertiary = "rgba(482537FF)"
M.tertiary_container = "rgba(613b4dFF)"
M.on_tertiary_container = "rgba(ffd8e7FF)"
M.error = "rgba(ffb4abFF)"
M.on_error = "rgba(690005FF)"
M.error_container = "rgba(93000aFF)"
M.on_error_container = "rgba(ffdad6FF)"
M.background = "rgba(141318FF)"
M.on_background = "rgba(e5e1e9FF)"
M.surface = "rgba(141318FF)"
M.on_surface = "rgba(e5e1e9FF)"
M.surface_variant = "rgba(47464fFF)"
M.on_surface_variant = "rgba(c9c5d0FF)"
M.outline = "rgba(928f99FF)"
M.outline_variant = "rgba(47464fFF)"

return M
