-- Generated by Matugen
local M = {}

M.primary = "rgba(cebdfeFF)"
M.on_primary = "rgba(35275dFF)"
M.primary_container = "rgba(4c3e76FF)"
M.on_primary_container = "rgba(e8ddffFF)"
M.secondary = "rgba(cbc3dcFF)"
M.on_secondary = "rgba(332e41FF)"
M.secondary_container = "rgba(494458FF)"
M.on_secondary_container = "rgba(e7def8FF)"
M.tertiary = "rgba(efb8c9FF)"
M.on_tertiary = "rgba(492533FF)"
M.tertiary_container = "rgba(633b49FF)"
M.on_tertiary_container = "rgba(ffd9e3FF)"
M.error = "rgba(ffb4abFF)"
M.on_error = "rgba(690005FF)"
M.error_container = "rgba(93000aFF)"
M.on_error_container = "rgba(ffdad6FF)"
M.background = "rgba(141318FF)"
M.on_background = "rgba(e6e1e9FF)"
M.surface = "rgba(141318FF)"
M.on_surface = "rgba(e6e1e9FF)"
M.surface_variant = "rgba(48454eFF)"
M.on_surface_variant = "rgba(cac4cfFF)"
M.outline = "rgba(938f99FF)"
M.outline_variant = "rgba(48454eFF)"

return M
