general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Screen dimming
listener {
    timeout = 300
    on-timeout = brightnessctl set 30%
    on-resume = brightnessctl set 100%
}

# Lock screen
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Turn off screen (DPMS)
listener {
    timeout = 660
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend
listener {
    timeout = 2700
    on-timeout = systemctl suspend
}
