return {
  "saghen/blink.cmp",
  dependencies = "rafamadriz/friendly-snippets",
  version = "*",
  opts = {
    keymap = {
      preset = "default",
      ["<Tab>"] = { "select_and_accept", "fallback" },
      ["<S-Tab>"] = { "select_prev", "fallback" },
    },
    appearance = {
      use_nvim_cmp_as_default = false,
      nerd_font_variant = "mono",
      kind_icons = {
        Text = "󰉿",
        Method = "󰊕",
        Function = "󰊕",
        Constructor = "󰆧",
        Field = "󰜢",
        Variable = "󰆦",
        Class = "󰠱",
        Interface = "󰕘",
        Module = "󰏗",
        Property = "󰜢",
        Unit = "󰑭",
        Value = "󰎠",
        Enum = "󰯍",
        Keyword = "󰌋",
        Snippet = "󰘍",
        Color = "󰏘",
        File = "󰈔",
        Reference = "󰬲",
        Folder = "󰉋",
        Event = "󱐋",
        Operator = "󰪚",
        TypeParameter = "󰬛",
      },
    },
    sources = { default = { "lsp", "path", "snippets", "buffer" } },
    completion = {
      ghost_text = { enabled = true },
      menu = { border = "rounded" },
      documentation = { auto_show = true, border = "rounded" },
      accept = {
        auto_brackets = {
          enabled = true,
          default_brackets = { "(", ")" },
        },
      },
    },
    signature = { enabled = true, window = { border = "rounded" } },
    cmdline = { enabled = true },
  },
  event = "InsertEnter",
}
