-- Generated by Matugen
local M = {}

M.primary = "rgba({{colors.primary.default.hex_stripped}}FF)"
M.on_primary = "rgba({{colors.on_primary.default.hex_stripped}}FF)"
M.primary_container = "rgba({{colors.primary_container.default.hex_stripped}}FF)"
M.on_primary_container = "rgba({{colors.on_primary_container.default.hex_stripped}}FF)"
M.secondary = "rgba({{colors.secondary.default.hex_stripped}}FF)"
M.on_secondary = "rgba({{colors.on_secondary.default.hex_stripped}}FF)"
M.secondary_container = "rgba({{colors.secondary_container.default.hex_stripped}}FF)"
M.on_secondary_container = "rgba({{colors.on_secondary_container.default.hex_stripped}}FF)"
M.tertiary = "rgba({{colors.tertiary.default.hex_stripped}}FF)"
M.on_tertiary = "rgba({{colors.on_tertiary.default.hex_stripped}}FF)"
M.tertiary_container = "rgba({{colors.tertiary_container.default.hex_stripped}}FF)"
M.on_tertiary_container = "rgba({{colors.on_tertiary_container.default.hex_stripped}}FF)"
M.error = "rgba({{colors.error.default.hex_stripped}}FF)"
M.on_error = "rgba({{colors.on_error.default.hex_stripped}}FF)"
M.error_container = "rgba({{colors.error_container.default.hex_stripped}}FF)"
M.on_error_container = "rgba({{colors.on_error_container.default.hex_stripped}}FF)"
M.background = "rgba({{colors.background.default.hex_stripped}}FF)"
M.on_background = "rgba({{colors.on_background.default.hex_stripped}}FF)"
M.surface = "rgba({{colors.surface.default.hex_stripped}}FF)"
M.on_surface = "rgba({{colors.on_surface.default.hex_stripped}}FF)"
M.surface_variant = "rgba({{colors.surface_variant.default.hex_stripped}}FF)"
M.on_surface_variant = "rgba({{colors.on_surface_variant.default.hex_stripped}}FF)"
M.outline = "rgba({{colors.outline.default.hex_stripped}}FF)"
M.outline_variant = "rgba({{colors.outline_variant.default.hex_stripped}}FF)"

return M
